--
-- File generated with SQLiteStudio v3.2.1 on mar ago 20 12:04:58 2024
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: generation
DROP TABLE IF EXISTS generation;
CREATE TABLE generation (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, population INTEGER NOT NULL DEFAULT (0), max_fitness DECIMAL NOT NULL DEFAULT (0));

-- Table: nodes
DROP TABLE IF EXISTS nodes;
CREATE TABLE nodes (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, x DECIMAL NOT NULL, y DECIMAL NOT NULL, constrain_x BOOLEAN NOT NULL DEFAULT (0), contrain_y BOOLEAN NOT NULL DEFAULT (0), u DECIMAL NOT NULL DEFAULT (0), v DECIMAL DEFAULT (0) NOT NULL);

-- Table: structures
DROP TABLE IF EXISTS structures;
CREATE TABLE structures (id INTEGER PRIMARY KEY ON CONFLICT FAIL AUTOINCREMENT NOT NULL UNIQUE, generation_id INTEGER NOT NULL REFERENCES generation (id) ON DELETE CASCADE ON UPDATE CASCADE);

-- Table: trusses
DROP TABLE IF EXISTS trusses;
CREATE TABLE trusses (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, structure_id INTEGER NOT NULL REFERENCES structures (id) ON DELETE CASCADE ON UPDATE CASCADE, area DECIMAL NOT NULL, mass DECIMAL NOT NULL, length DECIMAL NOT NULL, load DECIMAL NOT NULL DEFAULT (0), start_node INTEGER REFERENCES nodes (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, end_node INTEGER REFERENCES nodes (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
